on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        echo: "processing job1 ${{ github.job }}"

  job2:
    runs-on: ubuntu-latest
    steps:
    needs: job1
      - name: Checkout repository
        echo: "processing job2 ${{ github.job }}"

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Checkout repository
        echo: "processing job3 ${{ github.job }}"

  job4:
    runs-on: ubuntu-latest
    needs: [job3, job2]
    steps:
      - name: Checkout repository
        echo: "processing job4 ${{ github.job }}"
